---
apiVersion: v1
kind: Service

metadata:
  name: s3browser-server
  labels:
    app.kubernetes.io/name: s3browser
    app.kubernetes.io/component: server

spec:
  selector:
    app.kubernetes.io/name: s3browser
    app.kubernetes.io/component: server

  ports:
    - name: http
      port: 80

...
